version: "3"

services:
  node-app:
    image: node:14
    container_name: my-node-app
    env_file:
      - secrets.env
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    env_file:
      - secrets.env
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data: